# Generated by Django 4.2 on 2023-10-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Employee Name')),
                ('email', models.EmailField(max_length=277, verbose_name='Employee Email')),
                ('mobile', models.IntegerField(verbose_name='Employee Mobile')),
                ('department', models.TextField(max_length=200, verbose_name='Employee Department')),
                ('address', models.TextField(max_length=500, verbose_name='Employee Address')),
                ('dob', models.DateField(blank=True)),
                ('doj', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1)),
            ],
        ),
    ]
